name: Déploiement

on:
  push:
    tags: [ '**' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build WebService --no-restore /warnaserror -c Release
    - name: Setup Python
      uses: actions/setup-python@v4.7.1
      with:
        python-version: '3.11'
    - name: Install Paramiko
      run: python3 -m pip install paramiko
    - name: Deploy build
      env:
        DEPLOY_HOSTNAME: ${{ secrets.DEPLOY_HOSTNAME }}
        DEPLOY_USERNAME: ${{ secrets.DEPLOY_USERNAME }}
        DEPLOY_PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
      run: python3 .deployment/galliumplus-deploy