name: Vérifications

on:
  pull_request:
    branches: [ "main" ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    env:
      GALLIUM_ENV: test
      GALLIUM_HTTP: 5080
      GALLIUM_HTTPS: 5443
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build WebService --no-restore /warnaserror -c Release
    - name: Run unit tests
      run: dotnet test CoreTests
  
  api-tests:
    runs-on: ubuntu-latest
    env:
      GALLIUM_ENV: test
      GALLIUM_HTTP: 5080
      GALLIUM_HTTPS: 5443
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Fetch main branch
      run: git fetch --depth=1 origin main
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: '.tests/requirements.txt'
    - name: Install dependencies
      run: python3 -m pip install -r .tests/requirements.txt
    - name: Run API behavior tests
      run: python3 .tests/main.py --long-timeout
    - name: Run version check
      run: python3 .tests/check-version.py

      


    
